#应用端口
server:
  port: 8765

spring:
  application:
    name: service-feign #应用名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos服务地址
    sentinel:
      transport:
        dashboard: localhost:8080

#feign:
# sentinel:
#   enabled: true