#应用端口
server:
  port: 8764

spring:
  application:
    name: service-ribbon #应用名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos服务地址
    sentinel:
      transport:
        dashboard: localhost:8080